apiVersion: spec.keptn.sh/0.2.2
kind: "Shipyard"
metadata:
  name: "demo-webhook"
spec:
  stages:
    - name: "production"
      sequences:
      - name: "mysequence"
        tasks: 
        - name: "mytask-silent"
        - name: "evaluation"
          properties:
            timeframe: "5m"
      - name: "loadtesting"
        tasks: 
        - name: "disable-rate-limiting"
        - name: "execute-load-testing"
        - name: "enable-rate-limiting"
