apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.evaluation.finished
      requests:
        - curl --request POST --data
          '{"event":"{{.type}}","stage":"{{.data.stage}}","result":"{{.data.result}}
          ({{.data.evaluation.score}} / 100)"}'
          https://ld-stg.launchdarkly.com/webhook/triggers/620d6e33704a8d0c4011327b/7b6fd087-bbd9-4885-af18-3ec103069f34
      subscriptionID: a331e349-fd35-41e3-9765-ed57af74bf50
