apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.evaluation.finished
      requests:
        - curl --request POST --data
          '{"event":"{{.type}}","stage":"{{.data.stage}}","result":"{{.data.result}}
          ({{.data.evaluation.score}} / 100)"}'
          https://62395ee4cb207b6b7d8533ed567b7fc1.m.pipedream.net
      subscriptionID: 0059aa9c-4100-4f88-b186-2a1b3b90331e
    - type: sh.keptn.event.evaluation.finished
      requests:
        - curl --request POST --data
          '{"event_type":"silent","client_payload":{"type":"{{.type}}","project":"{{.data.project}}","service":"{{.data.service}}","stage":"{{.data.stage}}","shkeptncontext":"{{.shkeptncontext}}","id":"{{id}}"}}'
          https://ld-stg.launchdarkly.com/webhook/triggers/620d6e33704a8d0c4011327b/7b6fd087-bbd9-4885-af18-3ec103069f34
      subscriptionID: a331e349-fd35-41e3-9765-ed57af74bf50
