apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.evaluation.finished
      requests:
        - "curl --header 'Content-Type: application/json' --header
          'Authorization: {{.env.secret_cliffldlocal_authtoken}}' --request
          PATCH --data '{  \"patch\": [    {      \"op\":
          \"replace\",      \"path\":
          \"/environments/ctawiah-test/on\",      \"value\": {{$score := (index
          .data.evaluation.indicatorResults 1).score}}{{ if ge $score
          1.0}}true{{ else }}false{{ end }}    }  ],  \"comment\":
          \"{{.data.message}}\"}'
          https://sguduru-gonfalon.ngrok.io/api/v2/flags/default/ctawiah-test"
      envFrom:
        - name: secret_cliffldlocal_authtoken
          secretRef:
            name: cliff-ld-local
            key: auth-token
      subscriptionID: 6850dc25-91dd-4963-b87f-7e7364062698
    - type: sh.keptn.event.execute-load-testing.triggered
      sendFinished: true
      requests:
        - "curl --header 'Content-Type: application/json' --request POST --data
          '{\"eventName\":\"{{.type}}\",\"stage\":\"{{.data.stage}}\",\"context\
          Id\":\"{{.shkeptncontext}}\",\"url\":\"https://cyi56650.cloudautomati\
          on.live.dynatrace.com/bridge/project/{{.data.project}}/sequence/{{.sh\
          keptncontext}}/stage/{{.data.stage}}\"}'
          https://sguduru-gonfalon.ngrok.io/webhook/triggers/6215223e16f18d895f\
          9efedc/af740d71-9876-43bc-bdf2-2b49685ddc7a"
      subscriptionID: 0acb5b6d-8491-4570-9d4b-903c256b219a
    - type: sh.keptn.event.execute-load-testing.finished
      requests:
        - "curl --header 'Content-Type: application/json' --request POST --data
          '{\"eventName\":\"{{.type}}\",\"stage\":\"{{.data.stage}}\",\"context\
          Id\":\"{{.shkeptncontext}}\",\"url\":\"https://cyi56650.cloudautomati\
          on.live.dynatrace.com/bridge/project/{{.data.project}}/sequence/{{.sh\
          keptncontext}}/stage/{{.data.stage}}\"}'
          https://sguduru-gonfalon.ngrok.io/webhook/triggers/6215220f16f18d895f\
          9efed6/bea27d2c-deb4-4b06-8202-fb5de461c2fd"
      subscriptionID: 19900df1-3d75-4e5b-a3db-24450e645691
    - type: sh.keptn.event.evaluation.finished
      requests:
        - "curl --header 'Content-Type: application/json' --header
          'Authorization: {{.env.secret_sunnyldlocal_authtoken}}' --request
          PATCH --data '{  \"patch\": [    {      \"op\":
          \"replace\",      \"path\":
          \"/environments/production/on\",      \"value\": {{$score := (index
          .data.evaluation.indicatorResults 1).score}}{{ if ge $score
          1.0}}true{{ else }}false{{ end }}    }  ],  \"comment\":
          \"{{.data.message}}\"}'
          https://sguduru-gonfalon.ngrok.io/api/v2/flags/always-snippet/enable-\
          some-new-feature"
      envFrom:
        - name: secret_sunnyldlocal_authtoken
          secretRef:
            name: sunny-ld-local
            key: auth-token
      subscriptionID: 0059aa9c-4100-4f88-b186-2a1b3b90331e
    - type: sh.keptn.event.evaluation.finished
      requests:
        - "curl --header 'Content-Type: application/json' --header ': '
          --request POST --data
          '{\"event\":\"{{.type}}\",\"stage\":\"{{.data.stage}}\",\"result\":\"\
          {{.data.result}} ({{.data.evaluation.score}} / 100)\"}'
          http://sguduru-gonfalon.ngrok.io/webhook/triggers/624b67a99c015947664\
          52bec/75c4b697-3421-4c62-889b-5df4ecf2cf91"
      subscriptionID: a331e349-fd35-41e3-9765-ed57af74bf50
      sendFinished: false
