apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.evaluation.finished
      requests:
        - curl --request POST --data
          '{"event":"{{.type}}","stage":"{{.data.stage}}","result":"{{.data.result}}
          ({{.data.evaluation.score}} / 100)"}'
          https://ld-stg.launchdarkly.com/webhook/triggers/620d6e33704a8d0c4011327b/7b6fd087-bbd9-4885-af18-3ec103069f34
      subscriptionID: a331e349-fd35-41e3-9765-ed57af74bf50
    - type: sh.keptn.event.evaluation.finished
      requests:
        - "curl --header 'Content-Type: application/json' --request POST --data
          '{\"event\":\"{{.type}}\",\"stage\":\"{{.data.stage}}\",\"result\":\"\
          {{.data.result}} ({{.data.evaluation.score}} / 100)\"}'
          https://ld-ctawiah-2.ngrok.io/webhook/triggers/620d8f4c8b41fc6b62193c\
          e4/5391ce00-ddb9-4db1-8322-7d4e12cd06b8"
      subscriptionID: 0059aa9c-4100-4f88-b186-2a1b3b90331e
    - type: sh.keptn.event.evaluation.finished
      requests:
        - "curl --header 'Content-Type: application/json' --header
          'Authorization: {{.env.secret_cliffldlocal_authtoken}}' --request
          PATCH --data '{  \"patch\": [    {      \"op\":
          \"replace\",      \"path\":
          \"/environments/ctawiah-test/on\",      \"value\": {{$score := (index
          .data.evaluation.indicatorResults 1).score}}{{ if ge $score
          1.0}}true{{ else }}false{{ end }}    }  ],  \"comment\":
          \"{{.data.message}}\"}'
          https://ld-ctawiah-2.ngrok.io/api/v2/flags/default/ctawiah-test"
      envFrom:
        - name: secret_cliffldlocal_authtoken
          secretRef:
            name: cliff-ld-local
            key: auth-token
      subscriptionID: 6850dc25-91dd-4963-b87f-7e7364062698
    - type: sh.keptn.event.execute-load-testing.finished
      requests:
        - "curl --header 'Content-Type: application/json' --request POST --data
          '{  \"eventName\": \"{{.type}}\",  \"stage\":
          \"{{.data.stage}}\",  \"contextId\":
          \"{{.shkeptncontext}}\",  \"url\":
          \"https://cyi56650.cloudautomation.live.dynatrace.com/bridge/project/\
          {{.data.project}}/sequence/{{.shkeptncontext}}/stage/{{.data.stage}}\
          \", \"eventPayload\": {{.}}}'
          https://ld-ctawiah-2.ngrok.io/webhook/triggers/620f3a5d8b41fc1fe075a1\
          fd/8f0ceed1-31bc-4483-87b2-f962f861c99e"
      subscriptionID: 19900df1-3d75-4e5b-a3db-24450e645691
