apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.evaluation.triggered
      requests:
        - "curl --header 'Content-Type: application/json' --request PUT --data
          '{\"environmentKey\":\"production\",\"instructions\":[{\"kind\":\"tur\
          nFlagOn\"}],\"comment\":\"{{.data.message}}\"}'
          https://ld-ctawiah-2.ngrok.io/api/v2/flags/default/ctawiah-test"
      subscriptionID: 6850dc25-91dd-4963-b87f-7e7364062698
